<?php include_once '/../../header.php'; ?>

<?php include_once '/../../menu.php'; ?>

<div class="row">
<div class="row">
	<button type="button" class="btn btn-primary single"><a style="color:white" target="_blank" href="/expiration/public/reports/edit/<?= $data['report'][0]['report_id']?>"><span class="glyphicon glyphicon-pencil"></span> Edit</a></button>
	<button type="button" class="btn btn-primary single"><a style="color:white" target="_blank" href="/expiration/public/reports/duplicate/<?= $data['report'][0]['report_id']?>"><span class="glyphicon glyphicon-duplicate"></span> Duplicate</a></button>
	<button type="button" class="btn btn-primary single"><a style="color:white" target="_blank" href="/expiration/public/export/reportExport/<?= $data['report'][0]['report_id']?>"><span class="glyphicon glyphicon-export"></span> Export</a></button>
	<button type="button" class="btn btn-primary single"><a style="color:white" target="_blank" href="/expiration/public/reports"><span class="glyphicon glyphicon-arrow-left"></span> Back</a></button>
	<button type="button" class="btn btn-primary single"><a style="color:white" href="/expiration/public/reports/single/<?= $data['report_id']?>"><span class="glyphicon glyphicon-refresh"></span> Refresh</a></button>
</div>
<table class="table table-bordered">
	<thead>
	  	<tr><th colspan="20"><?= $data['report'][0]['name'] ?></th></tr>
	  	<tr>
	  		<th colspan="4">Report generated by : <?= $data['report'][0]['user_firstname']." ".$data['report'][0]['user_lastname']?></th>
	  		<th colspan="5">Timestamp : <?= date("D, F d-Y H:i:s",strtotime($data['report'][0]['timestamp']))?></th>
	  		<th colspan="4">Sales from : <?= $data['report'][0]['date_from']?></th>
	  		<th colspan="4">sales to : <?= $data['report'][0]['date_to']?></th>
	  		<th colspan="3">Number of items : <?= count($data['report'])?></th>
	  	</tr>
	  	<tr>
		  	<th>UPC</th>
		  	<th>VRD ITEM #</th>
		  	<th>ITEM DESCRIPTION</th>
		  	<th>PACK</th>
		  	<th>SIZE</th>
		  	<th>CASE COST</th>
		  	<th>RETAIL</th>
		  	<th>ON HAND</th>
		  	<th>ORDER QTY</th>
		  	<th>EXPIRATION</th>
		  	<th>EXP QTY UNIT</th>
		  	<th>LAST RECEIVING</th>
		  	<th>LAST RECEIVING DATE</th>
		  	<th>SALES</th>
		  	<th>TPR PRICE</th>
		  	<th>TPR START</th>
		  	<th>TPR END</th>
		  	<th>VDR NO</th>
		  	<th>VDR NAME</th>
		  	<th class="tdminus"></th>
	  	</tr>
	  </thead>
	  <tbody>
	  	<?php  
	  		if(!empty($data['report']))
		  	{
		  		$increment = 0; 
				$condition = 'ht' ;
		  		for($i=0;$i<count($data['report']);$i++)
		  		{
		  			if($data['report'][$i]['lastorder'] == ".0000")
		  			{
		  				$data['report'][$i]['lastorder'] = "";
		  			}
		  			else
		  			{
		  				$data['report'][$i]['lastorder'] = round($data['report'][$i]['lastorder']);
		  			}

		  			if($data['report'][$i]['tprprice'] == ".00")
		  			{
		  				 $data['report'][$i]['tprprice'] = '';
		  				 $data['report'][$i]['tprstart'] = '';
		  				 $data['report'][$i]['tprend'] = '';
		  			}
		  			if($increment == 0 || $condition != $data['report'][$i]['SctNo'])
			    	{
						echo '<tr class = "section_name">
						<td></td>
						<td></td>';
			            echo '<td class="SectionName">SECTION '.$data['report'][$i]['SctNo'].' - '.$data['report'][$i]['SctName'].'</td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>
			            <td></td>';
			            echo '</tr>';
					}
		  			echo "<tr id='".$data['report'][$i]['id']."'>";
		  			
		  			if(!empty($data['upcPriceCompare']) && $data['upc'] == $data['report'][$i]['upc'])
		  			{
		  				echo "<td>".$data['report'][$i]['upc']."</td>";
		  			}
		  			else
		  			{
		  				echo "<td><a href = '/expiration/public/reports/single/".$data['report_id']."/".$data['report'][$i]['upc']."'>".$data['report'][$i]['upc']."</a></td>";
		  			}
		  			echo "<td  class='certcode'>".$data['report'][$i]['itemcode']."</td>";
		  			echo "<td class='textLeft'>".$data['report'][$i]['description']."</td>";
		  			echo "<td>".$data['report'][$i]['pack']."</td>";
		  			echo "<td>".$data['report'][$i]['size']."</td>";
		  			echo "<td  class='casecost'>".number_format($data['report'][$i]['casecost'], 2, ".", "")."</td>";
		  			echo "<td>".number_format($data['report'][$i]['retail'], 2, ".", '')."</td>";
		  			if(round($data['report'][$i]['onhand']) < 0){
		  				echo "<td class='negative'>".round($data['report'][$i]['onhand'])."</td>";
		  			}else{
		  				echo "<td>".round($data['report'][$i]['onhand'])."</td>";
		  			}
		  			echo "<td class='orderqty'><input value='".$data['report'][$i]['orderqty']."' placeholder='Order qty' class='reportInput'></td>";
		  			echo "<td class='expiration_date'><input type='date' placeholder='Exp' class='reportInput expdate' value='".$data['report'][$i]['expiration_date']."'></td>";
		  			echo "<td class='expiration'><input type='text' placeholder='Exp Qty' class='reportInput' value='".$data['report'][$i]['expiration']."'></td>";
		  			echo "<td class='lo'>".$data['report'][$i]['lastorder']."</td>";
		  			echo "<td class='lod'>".$data['report'][$i]['lastorderdate']."</td>";
		  			echo "<td>".$data['report'][$i]['sales']."</td>";
		  			echo "<td>".$data['report'][$i]['tprprice']."</td>";
		  			echo "<td>".$data['report'][$i]['tprstart']."</td>";
		  			echo "<td>".$data['report'][$i]['tprend']."</td>";
		  			echo "<td class='vdrNo'>".$data['report'][$i]['vdrno']."</td>";
		  			echo "<td class='vdrName'>".$data['report'][$i]['vdrname']."</td>";
		  			echo "<td class = 'tdminus'><a href='/expiration/public/reports/delete_item/".$data['report'][$i]['id']."/".$data['report'][$i]['report_id']."'><span class='glyphicon glyphicon-minus'></span></a></td>";
		  			echo "</tr>";

		  			if(!empty($data['upcPriceCompare']) && $data['upc'] == $data['report'][$i]['upc'])
		  			{
		  				for($j=0;$j<count($data['upcPriceCompare']);$j++)
		  				{
		  					if($data['upcPriceCompare'][$j]['VdrName'] != $data['report'][$i]['vdrname'])
		  					{
		  						if($data['upcPriceCompare'][$j]['lastReceiving'] == ".0000")
					  			{
					  				$data['upcPriceCompare'][$j]['lastReceiving'] = "";
					  			}
					  			else
					  			{
					  				$data['upcPriceCompare'][$j]['lastReceiving'] = round($data['upcPriceCompare'][$j]['lastReceiving']);
					  			}

					  			if($data['upcPriceCompare'][$j]['tpr'] == ".00")
					  			{
					  				 $data['upcPriceCompare'][$j]['tpr'] = '';
					  				 $data['upcPriceCompare'][$j]['tprStart'] = '';
					  				 $data['upcPriceCompare'][$j]['tprEnd'] = '';
					  			}
			  					echo "<tr class='upcPriceCompareTr'>";
				  				echo "<td class = '".$data['report'][$i]['id']."'>".$data['upcPriceCompare'][$j]['UPC']."</td>";
					  			echo "<td  class = 'certcode'>".$data['upcPriceCompare'][$j]['CertCode']."</td>";
					  			echo "<td class = 'ItemDescription'>".$data['upcPriceCompare'][$j]['ItemDescription']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['Pack']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['SizeAlpha']."</td>";
					  			echo "<td class = 'casecost'>".number_format($data['upcPriceCompare'][$j]['CaseCost'], 2, ".", "")."</td>";
					  			echo "<td>".number_format($data['upcPriceCompare'][$j]['Retail'], 2, ".", '')."</td>";
					  			echo "<td>".round($data['upcPriceCompare'][$j]['onhand'])."</td>";
					  			echo "<td class='order'></td>";
					  			echo "<td class='expiration_date'></td>";
					  			echo "<td class='expiration'></td>";
					  			echo "<td class = 'lo'>".$data['upcPriceCompare'][$j]['lastReceiving']."</td>";
					  			echo "<td class = 'lod'>".$data['upcPriceCompare'][$j]['lastReceivingDate']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['sales']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['tpr']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['tprStart']."</td>";
					  			echo "<td>".$data['upcPriceCompare'][$j]['tprEnd']."</td>";
					  			echo "<td class = 'vendorno'>".$data['upcPriceCompare'][$j]['VdrNo']."</td>";
					  			echo "<td class = 'vendor'>".$data['upcPriceCompare'][$j]['VdrName']."</td>";
					  			echo "<td><span class='glyphicon glyphicon-credit-card'></span></td>";
				  				echo "</tr>";
		  					}
		  					
		  				}
		  				
		  			}
		  			$increment = $increment + 1 ;
    				$condition = $data['report'][$i]['SctNo'];
		  		}
		  	}
	  	?>
	  </tbody>
	  <tfoot>
		  	<tr><th colspan="20"></th></tr>
		  </tfoot>
</table>
</div>

<?php include_once '/../../footer.php'; ?>